### ISSUE TITLE
Recaptcha fails on page load on mobile

### ISSUE THREAD

**Issue by DavidTheSimon** [codeep/react-recaptcha-v3#10]
I test on Samsung Galaxy S6 and I receive the following error most of the times when I load the form page.

`Uncaught TypeError: window.grecaptcha.execute is not a function`

I use gatsby.js.

```
import {loadReCaptcha, ReCaptcha} from 'react-recaptcha-v3'

componentDidMount() {
    loadReCaptcha(captchaSiteId);
}

render() {
    <ReCaptcha
         sitekey={captchaSiteId}
         action='quoteForm'
         verifyCallback={this.onGoogleVerify}
    />
}
```

Does anyone experience this?

**Comment by dachinat** [comment]
It's on Chrome too

**Comment by yasinn** [comment]
still have this problem.

**Comment by yasinn** [comment]
> still have this problem.

Anyone who still have this problem in react-recaptcha-v3-global version. try use react-recaptcha-v3-universal 
That fork use www.recaptcha.net script and solve Uncaught TypeError: window.grecaptcha.execute is not a function problem by using upstream newest version.

**Comment by vlad-grigoryan** [comment]
Fixed
