### ISSUE TITLE
Load in first case - force to

### ISSUE THREAD

**Issue by ShintaroNippon** [codeep/react-recaptcha-v3#14]
Hi there, first of all, thanks by the new version updated.

Is there a way to force the re-captcha verification?

Because you have
"P.S. It will open the ReCaptcha window only when there are some doubts by Google; otherwise, it will automatically generate the captcha token."

This comes from google V3 by default?

Thanks
Shintaro

**Comment by styopdev** [comment]
Dear @ShintaroNippon, sorry for late response.
Regarding to google's documentation unfortunately it is not possible to open ReCaptcha programmatically at the moment.
