### ISSUE TITLE
Error: Invalid site key or not loaded in api.js: CORRECT_SITE_KEY

### ISSUE THREAD

**Issue by xijo** [codeep/react-recaptcha-v3#16]
Hello,

From time to time the following error occurs within our current recaptcha setup:

```Error: Invalid site key or not loaded in api.js: CORRECT_SITE_KEY```

It can be reproduced in IE11 when navigating to a page with recaptcha included, then navigating to another page (i.e. youtube) and then using browser back.

Although this path sounds obscure it happens from time to time and I can't be sure, that this is the only way to trigger it, it's just the only way I've found yet.

Did anyone else observe this behavior? Any suggestions for fixing or further debugging?

Thanks in advance,
Jo

**Comment by andyjohnharris** [comment]
@xijo I'm experiencing this error as well, specifically with IE11.

It looks like to me like it is loading the v2 recaptcha js.

Did you have any success in fixing this problem?

**Comment by rocketman-21** [comment]
Having this issue was well

**Comment by dontdomilk** [comment]
This is happening with us as well (even on initial load). It looks  like the package isn't being maintained though, so I'm probably going to find another one. 

Did anyone have any luck finding a fix?

**Comment by vlad-grigoryan** [comment]
@willhay @dontdomilk Can you check the last version of the plugin? Reopen the issue if it will be reproduced.

**Comment by voigtd** [comment]
This is still an issue with the latest version
