### ISSUE TITLE
How to reset?

### ISSUE THREAD

**Issue by Spenhouet** [codeep/react-recaptcha-v3#2]
On a error on my site I would like to reset the captcha.
How can I do this?

For your v2 project I found:

```
const recaptchaRef: any = React.createRef();
....
recaptchaRef.reset();
....
<ReCaptcha
    ref={recaptchaRef}
    ...
/>
```

But that only yields a `TypeError: recaptchaRef.reset is not a function`.

**Comment by Spenhouet** [comment]
@elinahovakimyan I would like to ping this.

**Comment by alexnedelcu** [comment]
Looking at the source it seems that you can get another token by calling:

recaptchaRef.current.execute()

However, since the developer's intention was not for 'execute' to be used as 'reset', this is not a reliable way do get a new token, as it may change in the future versions.

**Comment by morsaken** [comment]
`<ReCaptcha
    ref={ref => this.recaptcha = ref}
    sitekey={'RECAPTCHA_KEY'}
    action='social'
    verifyCallback={this.verifyCallback}
/>`

and use **this.recaptcha.execute()** to reset

**Comment by bionicvapourboy** [comment]
This is not possible when using ReCaptcha HOC:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `Component`.
    in withGoogleReCaptcha(GoogleReCaptcha) (created by Component)
```

**Comment by danielsalles** [comment]
The suggestions don't work. He is unable to execute the callback after the execute.

**Comment by uliana25** [comment]
How reset the captcha for the functional component?
