### ISSUE TITLE
The response is no longer valid: either is too old or has been used previously?

### ISSUE THREAD

**Issue by mifff-lunglinh** [codeep/react-recaptcha-v3#24]
Hi, i have a problem with captcha expride. How to reset token?

**Comment by vlad-grigoryan** [comment]
Hi to reset just use:
<ReCaptcha ref={ref => this.recaptcha = ref} sitekey={'RECAPTCHA_KEY'} action='social' verifyCallback={this.verifyCallback} />

and use this.recaptcha.execute() to reset
